#!/bin/bash
# lib/gpu_monitor.sh — GPU utilization monitoring for SLURM jobs
#
# Starts nvidia-smi sampling in background, generates summary on stop.
# Used by submit.sh to wrap GPU jobs automatically.

SLURMCTL_GPU_INTERVAL="${SLURMCTL_GPU_INTERVAL:-30}"  # seconds between samples

# Start GPU monitoring. Call before the job runs.
# Args: <log_dir> <job_id> <task_id>
gpu_monitor_start() {
  local log_dir="$1" job_id="$2" task_id="${3:-0}"
  local csv_path="${log_dir}/${job_id}_${task_id}_gpu.csv"

  # Only start if nvidia-smi is available
  if ! command -v nvidia-smi &>/dev/null; then
    return 0
  fi

  mkdir -p "$log_dir"

  nvidia-smi --query-gpu=timestamp,index,utilization.gpu,memory.used,memory.total,temperature.gpu,power.draw \
    --format=csv,noheader,nounits \
    -l "$SLURMCTL_GPU_INTERVAL" > "$csv_path" 2>/dev/null &
  SLURMCTL_GPU_PID=$!
  export SLURMCTL_GPU_PID
  export SLURMCTL_GPU_CSV="$csv_path"
  export SLURMCTL_GPU_SUMMARY="${log_dir}/${job_id}_${task_id}_gpu.summary"
}

# Stop GPU monitoring and write summary.
gpu_monitor_stop() {
  if [ -z "${SLURMCTL_GPU_PID:-}" ]; then
    return 0
  fi

  kill "$SLURMCTL_GPU_PID" 2>/dev/null
  wait "$SLURMCTL_GPU_PID" 2>/dev/null

  local csv="$SLURMCTL_GPU_CSV"
  local summary="$SLURMCTL_GPU_SUMMARY"

  if [ ! -s "$csv" ]; then
    return 0
  fi

  # Parse CSV: timestamp, gpu_idx, util%, mem_used_MiB, mem_total_MiB, temp_C, power_W
  awk -F', ' '
  NF >= 5 {
    n++
    u  += $3; if ($3 > mu) mu = $3
    m  += $4; if ($4 > mm) mm = $4
    mt  = $5
    if (NF >= 6) { t += $6; if ($6 > mt_max) mt_max = $6 }
    if (NF >= 7) { p += $7; if ($7 > mp) mp = $7 }
  }
  END {
    if (n == 0) exit
    printf "samples=%d\n", n
    printf "gpu_util_avg=%.1f\n", u/n
    printf "gpu_util_max=%.0f\n", mu
    printf "gpu_mem_avg_mib=%.0f\n", m/n
    printf "gpu_mem_max_mib=%.0f\n", mm
    printf "gpu_mem_total_mib=%.0f\n", mt
    printf "gpu_mem_pct=%.1f\n", (mm/mt)*100
    if (NF >= 6) printf "gpu_temp_avg=%.0f\n", t/n
    if (NF >= 6) printf "gpu_temp_max=%.0f\n", mt_max
    if (NF >= 7) printf "gpu_power_avg=%.0f\n", p/n
    if (NF >= 7) printf "gpu_power_max=%.0f\n", mp
  }' "$csv" > "$summary"
}

# Generate a wrapper script that monitors GPU around the real job.
# Args: <original_script> <log_dir>
# Prints the wrapper script path to stdout.
gpu_wrap_script() {
  local original="$1" log_dir="$2"
  local wrapper="${log_dir}/.slurmctl_gpu_wrapper_$$.sh"

  cat > "$wrapper" <<WRAPPER_EOF
#!/bin/bash
# Auto-generated by slurmctl — GPU monitoring wrapper
# Original script: $original

SLURMCTL_GPU_LIB="\$(dirname "\$0")/../lib/gpu_monitor.sh"
if [ -f "$SLURMCTL_SRC_DIR/lib/gpu_monitor.sh" ]; then
  source "$SLURMCTL_SRC_DIR/lib/gpu_monitor.sh"
elif [ -f "\$SLURMCTL_GPU_LIB" ]; then
  source "\$SLURMCTL_GPU_LIB"
fi

# Start monitoring
gpu_monitor_start "$log_dir" "\${SLURM_ARRAY_JOB_ID:-\$SLURM_JOB_ID}" "\${SLURM_ARRAY_TASK_ID:-0}"

# Run original script
bash "$original"
JOB_EXIT=\$?

# Stop monitoring and write summary
gpu_monitor_stop

exit \$JOB_EXIT
WRAPPER_EOF

  chmod +x "$wrapper"
  echo "$wrapper"
}
